logging:
  level:
    org:
      springframework:
        web: DEBUG
    com:
      isakov:
        encore: DEBUG
spring:
  flyway:
    locations: classpath:db.migration #value locations was "classpath:db/migration"
    enabled: true

  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: validate
