spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/em_db
        username: postgres
        password: 123
    flyway:
        enabled: false
isakov:
    hh:
        vacancy:
            base-url: https://api.hh.ru/vacancies
